export const reviews = [
  {
    name: "Jacob Snider",
    text: "Through its engaging and well-structured courses, Brilliant has taught me mathematical concepts that I previously struggled to understand. I now feel confident approaching both technical job interviews and real world problem solving situations. ",
    star: 5,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },
  {
    name: "Banjo bulldog",
    text: "Thanks guys for reminding me of the basics of science and emerging concepts shaping the world today!",
    star: 4,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },
  {
    name: "Frank Magnotti",
    text: "As an engineer, I find it very refreshing to use the brilliant app to keep my interdisciplinary knowledge up to date! It’s important to me to understand how principles from other disciplines can affect my designs and also my life overall!",
    star: 5,
    app: "",
    userType: "PROFESSIONALS",
  },
  {
    name: "startupper7777",
    text: "If you want to learn new things quickly and really understand the basic concepts, this is for you! I am an entrepreneur, needing to understand the basics of a lot of subjects at the same time and this is ideal for doing just that",
    star: 5,
    app: "App Store",
    userType: "PROFESSIONALS",
  },
  {
    name: "Viv W.",
    text: "This app is both super aesthetically and functionally pleasing and incredibly fun. I'm an engineer and like to stay fresh on a few skills that are a bit outside of my everyday use in my current job. This really hits the core of a concept and allows you to feel accomplished by actually learning and passing quizzes.",
    star: 5,
    app: "App Store",
    userType: "PROFESSIONALS",
  },
  {
    name: "Kem Andrson",
    text: "It's great for learning and sharpening skills. This app has been helpful with my performance at work and I feel more mentally active than before. Thank you so much devs.",
    star: 4,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },

  {
    name: "Banjo bulldog",
    text: "Thanks guys for reminding me of the basics of science and emerging concepts shaping the world today!",
    star: 4,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },
  {
    name: "David Warner",
    text: "It's great for learning and sharpening skills. This app has been helpful with my performance at work and I feel more mentally active than before. Thank you so much devs.",
    star: 4,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },
  {
    name: "Frank Magnotti",
    text: "As an engineer, I find it very refreshing to use the brilliant app to keep my interdisciplinary knowledge up to date! It’s important to me to understand how principles from other disciplines can affect my designs and also my life overall!",
    star: 5,
    app: "",
    userType: "PROFESSIONALS",
  },
  {
    name: "Steve",
    text: "If you want to learn new things quickly and really understand the basic concepts, this is for you! I am an entrepreneur, needing to understand the basics of a lot of subjects at the same time and this is ideal for doing just that",
    star: 5,
    app: "App Store",
    userType: "PROFESSIONALS",
  },
  {
    name: "Vichard",
    text: "This app is both super aesthetically and functionally pleasing and incredibly fun. I'm an engineer and like to stay fresh on a few skills that are a bit outside of my everyday use in my current job. This really hits the core of a concept and allows you to feel accomplished by actually learning and passing quizzes.",
    star: 5,
    app: "App Store",
    userType: "PROFESSIONALS",
  },
  {
    name: "Harry",
    text: "Through its engaging and well-structured courses, Brilliant has taught me mathematical concepts that I previously struggled to understand. I now feel confident approaching both technical job interviews and real world problem solving situations. ",
    star: 5,
    app: "Google Play",
    userType: "PROFESSIONALS",
  },
  {
    name: "Student 1",
    text: "Brilliant has made learning math enjoyable and easy to understand. The interactive lessons are engaging, and the step-by-step approach helped me grasp even the most challenging concepts. I love the instant feedback feature, which has boosted my confidence in solving problems.",
    star: 5,
    app: "Play Store",
    userType: "STUDENTS",
  },
  {
    name: "Student 2",
    text: "I used to struggle with math, but Brilliant's courses have helped me improve my skills significantly. The visual explanations and interactive examples make complex topics seem simple. The progress tracking feature motivates me to keep learning and improving.",
    star: 4,
    app: "App Store",
    userType: "STUDENTS",
  },
  {
    name: "Student 3",
    text: "The interactive lessons on Brilliant have made learning math fun and engaging for me. I love how I can practice problems at my own pace and receive instant feedback. Brilliant has transformed math from a challenging subject to one of my favorites!",
    star: 5,
    app: "App Store",
    userType: "STUDENTS",
  },
  {
    name: "Student 4",
    text: "Brilliant's courses are well-designed and easy to follow. They have helped me excel in math! The real-world applications of the concepts taught have made me appreciate the relevance of what I'm learning.",
    star: 5,
    app: "App Store",
    userType: "STUDENTS",
  },
  {
    name: "Student 5",
    text: "I recommend Brilliant to anyone struggling with math. It's a game-changer! The interactive approach and clear explanations make learning enjoyable and effective. I've seen a significant improvement in my grades since using Brilliant.",
    star: 5,
    app: "App Store",
    userType: "STUDENTS",
  },
  {
    name: "Student 6",
    text: "Brilliant's approach to teaching math is fantastic. I've seen a significant improvement in my grades. The step-by-step explanations and practice problems have made complex topics understandable. Brilliant has made math less intimidating and more enjoyable for me.",
    star: 4,
    app: "App Store",
    userType: "STUDENTS",
  },
  {
    name: "Teacher 1",
    text: "Brilliant has revolutionized how I teach math. My students are more engaged and motivated to learn! The interactive lessons and intuitive interface make teaching and learning a seamless experience. I highly recommend Brilliant to fellow educators.",
    star: 5,
    app: "Play Store",
    userType: "TEACHERS",
  },
  {
    name: "Teacher 2",
    text: "Using Brilliant's platform in my classroom has made a huge difference. It's interactive and effective! The variety of topics and the ability to track student progress are invaluable tools for teachers. Brilliant has become an essential part of my teaching toolkit.",
    star: 5,
    app: "Play Store",
    userType: "TEACHERS",
  },
  {
    name: "Teacher 3",
    text: "Brilliant's resources have helped me create dynamic lessons that resonate with my students. Highly recommended! The visual explanations and interactive examples make complex concepts easy to understand. Brilliant has transformed how I approach teaching math.",
    star: 5,
    app: "",
    userType: "TEACHERS",
  },
  {
    name: "Teacher 4",
    text: "I've been using Brilliant for a while now, and it has transformed how my students perceive math. It's a must-have! The step-by-step approach and interactive problems make learning engaging and effective. Brilliant has made math accessible to all students.",
    star: 5,
    app: "App Store",
    userType: "TEACHERS",
  },
  {
    name: "Teacher 5",
    text: "Brilliant's platform is a game-changer for educators. It simplifies complex concepts and makes learning fun! The interactive lessons and adaptive learning features cater to students of all levels. Brilliant has made teaching math more enjoyable and rewarding.",
    star: 5,
    app: "App Store",
    userType: "TEACHERS",
  },
  {
    name: "Teacher 6",
    text: "I've recommended Brilliant to all my colleagues. It's an invaluable tool for teaching math effectively! The comprehensive curriculum and interactive approach make learning engaging for students. Brilliant has helped me create a positive learning environment in my classroom.",
    star: 5,
    app: "App Store",
    userType: "TEACHERS",
  },
  {
    name: "Parent 1",
    text: "Brilliant has been instrumental in helping my child excel in math. The interactive lessons are fantastic! The progress tracking feature allows me to monitor my child's learning and provide support where needed. I highly recommend Brilliant to parents.",
    star: 5,
    app: "App Store",
    userType: "PARENTS",
  },
  {
    name: "Parent 2",
    text: "I'm impressed with Brilliant's approach to teaching math. It has made a noticeable difference in my child's learning. The interactive problems and clear explanations have helped my child understand complex topics. Brilliant is a valuable resource for parents.",
    star: 5,
    app: "App Store",
    userType: "PARENTS",
  },
  {
    name: "Parent 3",
    text: "Brilliant has made learning math enjoyable for my child. The progress is remarkable! The interactive lessons and gamified learning approach keep my child engaged and motivated. Brilliant has sparked a love for math in my child.",
    star: 5,
    app: "",
    userType: "PARENTS",
  },
  {
    name: "Parent 4",
    text: "My child loves using Brilliant to learn math. It's interactive and engaging, making learning fun! The step-by-step explanations and interactive problems have improved my child's understanding of math concepts. Brilliant is a fantastic tool for parents.",
    star: 5,
    app: "App Store",
    userType: "PARENTS",
  },
  {
    name: "Parent 5",
    text: "Brilliant's platform has exceeded my expectations. It's a valuable resource for parents who want to support their child's education. The personalized learning experience and progress tracking feature make it easy for parents to monitor their child's progress.",
    star: 5,
    app: "App Store",
    userType: "PARENTS",
  },
  {
    name: "Parent 6",
    text: "I highly recommend Brilliant to parents looking to enhance their child's math skills. It's user-friendly and effective! The interactive lessons and adaptive learning features cater to each child's learning pace. Brilliant has made learning math enjoyable for my child.",
    star: 4,
    app: "App Store",
    userType: "PARENTS",
  },
  {
    name: "Lifelong Learner 1",
    text: "Brilliant has been a valuable resource for my continuous learning journey. The diverse range of topics and interactive lessons have kept me engaged and motivated. I appreciate the flexibility to learn at my own pace and explore new concepts.",
    star: 5,
    app: "Play Store",
    userType: "LIFE LONG LEARNERS",
  },
  {
    name: "Lifelong Learner 2",
    text: "I've always believed in lifelong learning, and Brilliant has been a perfect companion on this journey. The well-structured courses and challenging problems have expanded my knowledge and critical thinking skills. I highly recommend Brilliant to fellow lifelong learners.",
    star: 5,
    app: "App Store",
    userType: "LIFE LONG LEARNERS",
  },
  {
    name: "Lifelong Learner 3",
    text: "Brilliant's platform has reignited my passion for learning. The interactive nature of the courses and the community aspect make learning engaging and enjoyable. I'm constantly impressed by the depth and quality of content on Brilliant.",
    star: 5,
    app: "Play Store",
    userType: "LIFE LONG LEARNERS",
  },
  {
    name: "Lifelong Learner 4",
    text: "As a lifelong learner, I value platforms like Brilliant that offer in-depth knowledge and practical applications. The ability to learn from experts and peers enhances the learning experience. Brilliant has become my go-to platform for continuous education.",
    star: 4,
    app: "Play Store",
    userType: "LIFE LONG LEARNERS",
  },
  {
    name: "Lifelong Learner 5",
    text: "Brilliant's approach to learning is perfect for lifelong learners like me. The interactive courses and challenging problems keep me intellectually stimulated. I've gained a deeper understanding of various subjects thanks to Brilliant.",
    star: 5,
    app: "App Store",
    userType: "LIFE LONG LEARNERS",
  },
  {
    name: "Lifelong Learner 6",
    text: "I've recommended Brilliant to all my fellow lifelong learners. The platform's interactive nature and diverse course offerings make it a top choice for continuous education. Brilliant has helped me expand my knowledge and skills in various areas.",
    star: 4,
    app: "App Store",
    userType: "LIFE LONG LEARNERS",
  },
];
